# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: "Hello, this is a NaVi-KV. Available commands are: build, test"

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    cmds:
      - go build ./cmd/navi-cli
  run-cli:
    cmds:
      - ./navi-cli
  test:
    desc: Run all tests with the race detector
    cmds:
      - go test ./... -race
